cp:
    resource: "@CPBundle/Resources/config/routing.yml"
    prefix:   /

site:
    resource: "@CPBundle/Controller"
    type:     annotation

rest:
  type: rest
  resource: "routing_rest.yml"
  prefix: /api