parameters:
#    cp.example.class: CivPlanet\Bundle\Example

services:
#    cp.example:
#        class: %cp.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


    civplanet.player_manager:
        class: CivPlanet\Bundle\Manager\PlayerManager
        arguments: [@doctrine.orm.entity_manager]

    civplanet.session_manager:
        class: CivPlanet\Bundle\Manager\SessionManager
        arguments: [@doctrine.orm.entity_manager]

    civplanet.event_manager:
        class: CivPlanet\Bundle\Manager\EventManager
        arguments: [@doctrine.orm.entity_manager]