players:
  type: rest
  resource: "CPBundle:APIPlayer"
  name_prefix:  api_

sessions:
  type: rest
  resource: "CPBundle:APISession"
  name_prefix: api_

events:
  type: rest
  resource: "CPBundle:APIEvent"
  name_prefix: api_